// Mocks generated by Mockito 5.4.6 from annotations
// in surf_mad_teacher_training/test/widget/feature/common/presentation/widgets/favorites/favorites_button_widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:flutter/foundation.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:surf_mad_teacher_training/feature/common/domain/entities/place_entity.dart'
    as _i4;
import 'package:surf_mad_teacher_training/feature/common/presentation/widgets/favorites/favorites_button_wm.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeValueListenable_0<T> extends _i1.SmartFake
    implements _i2.ValueListenable<T> {
  _FakeValueListenable_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [IFavoritesButtonWM].
///
/// See the documentation for Mockito's code generation for more information.
class MockIFavoritesButtonWM extends _i1.Mock
    implements _i3.IFavoritesButtonWM {
  MockIFavoritesButtonWM() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ValueListenable<bool> get isFavoriteState =>
      (super.noSuchMethod(
            Invocation.getter(#isFavoriteState),
            returnValue: _FakeValueListenable_0<bool>(
              this,
              Invocation.getter(#isFavoriteState),
            ),
          )
          as _i2.ValueListenable<bool>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void onFavoritePressed(_i4.PlaceEntity? place) => super.noSuchMethod(
    Invocation.method(#onFavoritePressed, [place]),
    returnValueForMissingStub: null,
  );
}
