// Mocks generated by Mockito 5.4.6 from annotations
// in surf_mad_teacher_training/test/widget/common/presentation/widgets/places/place_card_widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:dio/dio.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i14;
import 'package:rxdart/rxdart.dart' as _i9;
import 'package:shared_preferences/shared_preferences.dart' as _i3;
import 'package:surf_mad_teacher_training/api/data/filter_places_request_dto.dart'
    as _i13;
import 'package:surf_mad_teacher_training/api/data/place_dto.dart' as _i16;
import 'package:surf_mad_teacher_training/api/service/api_client.dart' as _i6;
import 'package:surf_mad_teacher_training/core/data/converter/converter.dart'
    as _i11;
import 'package:surf_mad_teacher_training/feature/app/di/app_scope.dart'
    as _i10;
import 'package:surf_mad_teacher_training/feature/common/domain/entities/place_entity.dart'
    as _i15;
import 'package:surf_mad_teacher_training/feature/common/domain/repositories/i_favorites_repository.dart'
    as _i8;
import 'package:surf_mad_teacher_training/feature/filter/domain/entities/filter_places_entity.dart'
    as _i12;
import 'package:surf_mad_teacher_training/feature/theme_mode/domain/repositories/i_theme_mode_repository.dart'
    as _i7;
import 'package:surf_mad_teacher_training/persistence/database/app_database.dart'
    as _i2;
import 'package:surf_mad_teacher_training/persistence/filter_storage/i_filter_storage.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAppDatabase_0 extends _i1.SmartFake implements _i2.AppDatabase {
  _FakeAppDatabase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSharedPreferences_1 extends _i1.SmartFake
    implements _i3.SharedPreferences {
  _FakeSharedPreferences_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIFilterStorage_2 extends _i1.SmartFake
    implements _i4.IFilterStorage {
  _FakeIFilterStorage_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDio_3 extends _i1.SmartFake implements _i5.Dio {
  _FakeDio_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeApiClient_4 extends _i1.SmartFake implements _i6.ApiClient {
  _FakeApiClient_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIThemeModeRepository_5 extends _i1.SmartFake
    implements _i7.IThemeModeRepository {
  _FakeIThemeModeRepository_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIFavoritesRepository_6 extends _i1.SmartFake
    implements _i8.IFavoritesRepository {
  _FakeIFavoritesRepository_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeValueStream_7<T> extends _i1.SmartFake
    implements _i9.ValueStream<T> {
  _FakeValueStream_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [IAppScope].
///
/// See the documentation for Mockito's code generation for more information.
class MockIAppScope extends _i1.Mock implements _i10.IAppScope {
  MockIAppScope() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AppDatabase get appDatabase =>
      (super.noSuchMethod(
            Invocation.getter(#appDatabase),
            returnValue: _FakeAppDatabase_0(
              this,
              Invocation.getter(#appDatabase),
            ),
          )
          as _i2.AppDatabase);

  @override
  _i3.SharedPreferences get sharedPreferences =>
      (super.noSuchMethod(
            Invocation.getter(#sharedPreferences),
            returnValue: _FakeSharedPreferences_1(
              this,
              Invocation.getter(#sharedPreferences),
            ),
          )
          as _i3.SharedPreferences);

  @override
  _i4.IFilterStorage get filterStorage =>
      (super.noSuchMethod(
            Invocation.getter(#filterStorage),
            returnValue: _FakeIFilterStorage_2(
              this,
              Invocation.getter(#filterStorage),
            ),
          )
          as _i4.IFilterStorage);

  @override
  _i5.Dio get dio =>
      (super.noSuchMethod(
            Invocation.getter(#dio),
            returnValue: _FakeDio_3(this, Invocation.getter(#dio)),
          )
          as _i5.Dio);

  @override
  _i6.ApiClient get apiClient =>
      (super.noSuchMethod(
            Invocation.getter(#apiClient),
            returnValue: _FakeApiClient_4(this, Invocation.getter(#apiClient)),
          )
          as _i6.ApiClient);

  @override
  _i7.IThemeModeRepository get themeModeRepository =>
      (super.noSuchMethod(
            Invocation.getter(#themeModeRepository),
            returnValue: _FakeIThemeModeRepository_5(
              this,
              Invocation.getter(#themeModeRepository),
            ),
          )
          as _i7.IThemeModeRepository);

  @override
  _i11.ConverterToAndFrom<_i12.FilterPlacesEntity, _i13.FilterPlacesRequestDto>
  get filterPlacesConverter =>
      (super.noSuchMethod(
            Invocation.getter(#filterPlacesConverter),
            returnValue: _i14.dummyValue<
              _i11.ConverterToAndFrom<
                _i12.FilterPlacesEntity,
                _i13.FilterPlacesRequestDto
              >
            >(this, Invocation.getter(#filterPlacesConverter)),
          )
          as _i11.ConverterToAndFrom<
            _i12.FilterPlacesEntity,
            _i13.FilterPlacesRequestDto
          >);

  @override
  _i11.Converter<_i15.PlaceEntity, _i16.PlaceDto> get placeResponseConverter =>
      (super.noSuchMethod(
            Invocation.getter(#placeResponseConverter),
            returnValue: _i14
                .dummyValue<_i11.Converter<_i15.PlaceEntity, _i16.PlaceDto>>(
                  this,
                  Invocation.getter(#placeResponseConverter),
                ),
          )
          as _i11.Converter<_i15.PlaceEntity, _i16.PlaceDto>);

  @override
  _i8.IFavoritesRepository get favoritesRepository =>
      (super.noSuchMethod(
            Invocation.getter(#favoritesRepository),
            returnValue: _FakeIFavoritesRepository_6(
              this,
              Invocation.getter(#favoritesRepository),
            ),
          )
          as _i8.IFavoritesRepository);

  @override
  _i11.Converter<_i15.PlaceEntity, _i2.FavoritePlacesTableData>
  get favoriteFromDbConverter =>
      (super.noSuchMethod(
            Invocation.getter(#favoriteFromDbConverter),
            returnValue: _i14.dummyValue<
              _i11.Converter<_i15.PlaceEntity, _i2.FavoritePlacesTableData>
            >(this, Invocation.getter(#favoriteFromDbConverter)),
          )
          as _i11.Converter<_i15.PlaceEntity, _i2.FavoritePlacesTableData>);

  @override
  _i11.Converter<_i2.FavoritePlacesTableCompanion, _i15.PlaceEntity>
  get favoriteToDbConverter =>
      (super.noSuchMethod(
            Invocation.getter(#favoriteToDbConverter),
            returnValue: _i14.dummyValue<
              _i11.Converter<_i2.FavoritePlacesTableCompanion, _i15.PlaceEntity>
            >(this, Invocation.getter(#favoriteToDbConverter)),
          )
          as _i11.Converter<
            _i2.FavoritePlacesTableCompanion,
            _i15.PlaceEntity
          >);
}

/// A class which mocks [IFavoritesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIFavoritesRepository extends _i1.Mock
    implements _i8.IFavoritesRepository {
  MockIFavoritesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.ValueStream<List<_i15.PlaceEntity>> get favoritesStream =>
      (super.noSuchMethod(
            Invocation.getter(#favoritesStream),
            returnValue: _FakeValueStream_7<List<_i15.PlaceEntity>>(
              this,
              Invocation.getter(#favoritesStream),
            ),
          )
          as _i9.ValueStream<List<_i15.PlaceEntity>>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void toggleFavorite(_i15.PlaceEntity? place) => super.noSuchMethod(
    Invocation.method(#toggleFavorite, [place]),
    returnValueForMissingStub: null,
  );
}
