// Mocks generated by Mockito 5.4.6 from annotations
// in surf_mad_teacher_training/test/unit/feature/places/data/repositories/places_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:surf_mad_teacher_training/api/data/filter_places_request_dto.dart'
    as _i2;
import 'package:surf_mad_teacher_training/api/data/place_dto.dart' as _i5;
import 'package:surf_mad_teacher_training/api/service/api_client.dart' as _i3;
import 'package:surf_mad_teacher_training/persistence/filter_storage/i_filter_storage.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFilterPlacesRequestDto_0 extends _i1.SmartFake
    implements _i2.FilterPlacesRequestDto {
  _FakeFilterPlacesRequestDto_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i3.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.PlaceDto>> getFilteredPlaces({
    required _i2.FilterPlacesRequestDto? filter,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getFilteredPlaces, [], {#filter: filter}),
            returnValue: _i4.Future<List<_i5.PlaceDto>>.value(<_i5.PlaceDto>[]),
          )
          as _i4.Future<List<_i5.PlaceDto>>);

  @override
  _i4.Future<List<_i5.PlaceDto>> getPlaces() =>
      (super.noSuchMethod(
            Invocation.method(#getPlaces, []),
            returnValue: _i4.Future<List<_i5.PlaceDto>>.value(<_i5.PlaceDto>[]),
          )
          as _i4.Future<List<_i5.PlaceDto>>);
}

/// A class which mocks [IFilterStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockIFilterStorage extends _i1.Mock implements _i6.IFilterStorage {
  MockIFilterStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> clear() =>
      (super.noSuchMethod(
            Invocation.method(#clear, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.FilterPlacesRequestDto> getFilter() =>
      (super.noSuchMethod(
            Invocation.method(#getFilter, []),
            returnValue: _i4.Future<_i2.FilterPlacesRequestDto>.value(
              _FakeFilterPlacesRequestDto_0(
                this,
                Invocation.method(#getFilter, []),
              ),
            ),
          )
          as _i4.Future<_i2.FilterPlacesRequestDto>);

  @override
  _i4.Future<void> saveFilter({
    required _i2.FilterPlacesRequestDto? filterDto,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveFilter, [], {#filterDto: filterDto}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
