// Mocks generated by Mockito 5.4.6 from annotations
// in surf_mad_teacher_training/test/unit/feature/settings/presentation/settings_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flutter/material.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:rxdart/rxdart.dart' as _i2;
import 'package:surf_mad_teacher_training/feature/theme_mode/domain/repositories/i_theme_mode_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeValueStream_0<T> extends _i1.SmartFake
    implements _i2.ValueStream<T> {
  _FakeValueStream_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [IThemeModeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIThemeModeRepository extends _i1.Mock
    implements _i3.IThemeModeRepository {
  MockIThemeModeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ValueStream<_i4.ThemeMode> get themeModeStream =>
      (super.noSuchMethod(
            Invocation.getter(#themeModeStream),
            returnValue: _FakeValueStream_0<_i4.ThemeMode>(
              this,
              Invocation.getter(#themeModeStream),
            ),
          )
          as _i2.ValueStream<_i4.ThemeMode>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<_i4.ThemeMode> getThemeMode() =>
      (super.noSuchMethod(
            Invocation.method(#getThemeMode, []),
            returnValue: _i5.Future<_i4.ThemeMode>.value(_i4.ThemeMode.system),
          )
          as _i5.Future<_i4.ThemeMode>);

  @override
  _i5.Future<void> setThemeMode(_i4.ThemeMode? newThemeMode) =>
      (super.noSuchMethod(
            Invocation.method(#setThemeMode, [newThemeMode]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
